# Generated by Django 3.2.4 on 2021-06-16 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fifteen_left',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='sixty_left',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='zero_left',
            field=models.BooleanField(default=False),
        ),
    ]
