# Generated by Django 3.1.7 on 2021-05-21 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=None, max_length=50)),
                ('acht_1', models.BooleanField(default=False)),
                ('acht_2', models.BooleanField(default=False)),
                ('acht_3', models.BooleanField(default=False)),
                ('acht_4', models.BooleanField(default=False)),
                ('neun_1', models.BooleanField(default=False)),
                ('neun_2', models.BooleanField(default=False)),
                ('neun_3', models.BooleanField(default=False)),
                ('neun_4', models.BooleanField(default=False)),
                ('zehn_1', models.BooleanField(default=False)),
                ('zehn_2', models.BooleanField(default=False)),
                ('zehn_3', models.BooleanField(default=False)),
                ('zehn_4', models.BooleanField(default=False)),
                ('elf_1', models.BooleanField(default=False)),
                ('elf_2', models.BooleanField(default=False)),
                ('elf_3', models.BooleanField(default=False)),
                ('elf_4', models.BooleanField(default=False)),
                ('zwölf_1', models.BooleanField(default=False)),
                ('zwölf_2', models.BooleanField(default=False)),
                ('zwölf_3', models.BooleanField(default=False)),
                ('zwölf_4', models.BooleanField(default=False)),
                ('dreizehn_1', models.BooleanField(default=False)),
                ('dreizehn_2', models.BooleanField(default=False)),
                ('dreizehn_3', models.BooleanField(default=False)),
                ('dreizehn_4', models.BooleanField(default=False)),
                ('vierzehn_1', models.BooleanField(default=False)),
                ('vierzehn_2', models.BooleanField(default=False)),
                ('vierzehn_3', models.BooleanField(default=False)),
                ('vierzehn_4', models.BooleanField(default=False)),
                ('fünfzehn_1', models.BooleanField(default=False)),
                ('fünfzehn_2', models.BooleanField(default=False)),
                ('fünfzehn_3', models.BooleanField(default=False)),
                ('fünfzehn_4', models.BooleanField(default=False)),
                ('sechzehn_1', models.BooleanField(default=False)),
                ('sechzehn_2', models.BooleanField(default=False)),
                ('sechzehn_3', models.BooleanField(default=False)),
                ('sechzehn_4', models.BooleanField(default=False)),
                ('siebzehn_1', models.BooleanField(default=False)),
                ('siebzehn_2', models.BooleanField(default=False)),
                ('siebzehn_3', models.BooleanField(default=False)),
                ('siebzehn_4', models.BooleanField(default=False)),
                ('achtzehn_1', models.BooleanField(default=False)),
                ('achtzehn_2', models.BooleanField(default=False)),
                ('achtzehn_3', models.BooleanField(default=False)),
                ('achtzehn_4', models.BooleanField(default=False)),
                ('neunzehn_1', models.BooleanField(default=False)),
                ('neunzehn_2', models.BooleanField(default=False)),
                ('neunzehn_3', models.BooleanField(default=False)),
                ('neunzehn_4', models.BooleanField(default=False)),
                ('zwanzig_1', models.BooleanField(default=False)),
                ('zwanzig_2', models.BooleanField(default=False)),
                ('zwanzig_3', models.BooleanField(default=False)),
                ('zwanzig_4', models.BooleanField(default=False)),
            ],
        ),
    ]
